// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpWP5Ru-lCR2nR94_FBi425aAGQv-fiL4',
    appId: '1:237815020451:web:d236677b01f7a1db5ff816',
    messagingSenderId: '237815020451',
    projectId: 'nutriapp-ce3b8',
    authDomain: 'nutriapp-ce3b8.firebaseapp.com',
    storageBucket: 'nutriapp-ce3b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9VVTDZ2Q0t6yVDwy5O-CCpSydAPsn6iY',
    appId: '1:237815020451:android:797d674c10d61d115ff816',
    messagingSenderId: '237815020451',
    projectId: 'nutriapp-ce3b8',
    storageBucket: 'nutriapp-ce3b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNLsj_k6TD3y0_FpU2C45bhBnOtLuJ6oY',
    appId: '1:237815020451:ios:880cf67676be52305ff816',
    messagingSenderId: '237815020451',
    projectId: 'nutriapp-ce3b8',
    storageBucket: 'nutriapp-ce3b8.appspot.com',
    androidClientId:
        '237815020451-9pcf0d9c1d78n0br2b51dh7lsfmmpqjv.apps.googleusercontent.com',
    iosClientId:
        '237815020451-rq9dltc4n42aruubgne0uommumast11g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNLsj_k6TD3y0_FpU2C45bhBnOtLuJ6oY',
    appId: '1:237815020451:ios:880cf67676be52305ff816',
    messagingSenderId: '237815020451',
    projectId: 'nutriapp-ce3b8',
    storageBucket: 'nutriapp-ce3b8.appspot.com',
    androidClientId:
        '237815020451-9pcf0d9c1d78n0br2b51dh7lsfmmpqjv.apps.googleusercontent.com',
    iosClientId:
        '237815020451-rq9dltc4n42aruubgne0uommumast11g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
